spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/jancoblog?serverTimezone=UTC&characterEncoding=utf-8
    url: jdbc:mysql://101.201.64.102/jancoblog?serverTimezone=UTC&characterEncoding=utf-8
    username: jancoblog
#    username: root
    password: 333
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    view:
      prefix: /
      suffix: .html
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
  redis:
    host: 101.201.64.102
    port: 6379
    password: 333
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080
  max-http-header-size: 1MB

#logging:
#  level:
#    com.jancoyan.jancoblog.mapper: debug
