spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jancoblog?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 333
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    view:
      suffix: .html
      prefix: classpath:/templates/
    static-path-pattern: /**
  servlet:
    multipart:
      location: classpath:/static/web-imgs/
    web:
      resources:
        static-locations: classpath:public/, file:${spring.servlet.multipart.location}

server:
  port: 8080

logging:
  level:
    com.jancoyan.mapper: debug