jar:
   fileUrl: /home/jancoyan/springbootApp/blog/static

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/jancoblog?serverTimezone=UTC&characterEncoding=utf-8
    username: jancoblog
    password: 333
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    view:
      prefix: /
      suffix: .html
  web:
    resources:
      static-locations: file:${jar.fileUrl},classpath:/static/,
  redis:
    host: demo.evilemperor.top
    port: 9001
    password: 333
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  max-http-header-size: 1MB
  port: 8000
